plugins {
    id 'com.android.library' version '8.4.0'
    id 'org.jetbrains.kotlin.android' version '1.9.21'
    id 'maven-publish'
}

group = 'com.infodreams.remotelogger'
version = '0.1.6'

ext.kotlin_version = '1.9.0'


android {
    namespace 'com.infodreams.remotelogger'
    compileSdkVersion 34

    defaultConfig {
        minSdkVersion 21
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    
    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'com.google.code.gson:gson:2.10.1'

    // Firebase (compileOnly to avoid forcing dependency)
    compileOnly 'com.google.firebase:firebase-storage:20.3.0'
    compileOnly 'com.google.firebase:firebase-firestore:24.10.0'
    compileOnly 'org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.7.3'

    // Supabase (compileOnly)
    compileOnly 'io.github.jan-tennert.supabase:storage-kt:2.5.0'
    compileOnly 'io.github.jan-tennert.supabase:postgrest-kt:2.5.0'

    // Testing
    testImplementation 'junit:junit:4.13.2'
    testImplementation "org.jetbrains.kotlin:kotlin-test-junit:$kotlin_version"
    testImplementation "io.mockk:mockk:1.13.8"
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release
                groupId = 'com.github.infodreams-software'
                artifactId = 'android-remote-logger'
                version = '0.1.6'
            }
        }
    }
}
